apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost-docker-db-deployment
  labels:
    app: mattermost-docker-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mattermost-docker-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mattermost-docker-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: mattermost
        - name: POSTGRES_PASSWORD
          value: mmuser_password
        - name: POSTGRES_USER
          value: mmuser
        image: teamjupitergmu/mattermost-docker:db-39
        name: mattermost-docker-db
        ports:
          - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-claim0
        - mountPath: /etc/localtime
          name: db-claim1
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: db-claim0
        persistentVolumeClaim:
          claimName: db-claim0
      - name: db-claim1
        persistentVolumeClaim:
          claimName: db-claim1
          readOnly: true
status: {}
