apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - env:
        - name: MM_DBNAME
          value: mattermost
        - name: MM_PASSWORD
          value: mmuser_password
        - name: MM_SQLSETTINGS_DATASOURCE
          value: postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10
        - name: MM_USERNAME
          value: mmuser
        image: teamjupitergmu/mattermost-docker:app-38
        name: app
        resources: {}
        volumeMounts:
        - mountPath: /mattermost/config
          name: app-claim0
        - mountPath: /mattermost/data
          name: app-claim1
        - mountPath: /mattermost/logs
          name: app-claim2
        - mountPath: /mattermost/plugins
          name: app-claim3
        - mountPath: /mattermost/client/plugins
          name: app-claim4
        - mountPath: /etc/localtime
          name: app-claim5
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: app-claim0
        persistentVolumeClaim:
          claimName: app-claim0
      - name: app-claim1
        persistentVolumeClaim:
          claimName: app-claim1
      - name: app-claim2
        persistentVolumeClaim:
          claimName: app-claim2
      - name: app-claim3
        persistentVolumeClaim:
          claimName: app-claim3
      - name: app-claim4
        persistentVolumeClaim:
          claimName: app-claim4
      - name: app-claim5
        persistentVolumeClaim:
          claimName: app-claim5
          readOnly: true
status: {}
